linters:
  default: standard
  enable:
    - cyclop
    - gocritic
    - gosec
    - ineffassign
    - misspell
    - prealloc
    - unconvert
    - unparam
    - whitespace

linters-settings:
  cyclop:
    # the maximal code complexity to report
    max-complexity: 30
    # the maximal average package complexity. If it's higher than 0.0 (float) the check is enabled (default 0.0)
    package-average: 0.0
    # should ignore tests (default false)
    skip-tests: true

formatters:
  enable:
    - gofumpt
    - goimports

output:
  print-issued-lines: true
  print-config: true